name: example_proportional_design
description: Example app for proportional_design package

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  proportional_design:
    path: ../
