name: proportional_widget
description: Allows proportional widget responsiveness
version: 1.0.0
#author: Matheus Perez <matheuslperez@gmail.com>
homepage: https://github.com/matheusperez/proportional-widget

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

