name: proportional_design
description: Allows proportional and responsive design
version: 1.0.0
#author: Matheus Perez <matheuslperez@gmail.com>
homepage: https://github.com/matheusperez/proportional-widget

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
